easy_admin:
  site_name: Conference Guestbook

  design:
    menu:
      - { route: "conference-list", label: "Back to the website", icon: "home" }
      - { entity: "Conference", label: "Conferences", icon: "map-marker" }
      - { entity: "Comment", label: "Comments", icon: "comments" }

  entities:
    Conference:
      class: App\Entity\Conference
      form:
        fields:
          - "city"
          - "year"
          - "isInternational"

    Comment:
      class: App\Entity\Comment
      list:
        fields:
          - author
          - { property: "email", type: "email" }
          - { property: 'photoFilename', type: 'image', 'base_path': "/uploads/photos", label: 'Photo' }
          - state
          - { property: "createdAt", type: "datetime" }
          - conference
        sort: ["createdAt", "ASC"]
        filters: ["conference", "email"]
      form:
        fields:
          - "conference"
          - {
              property: "createdAt",
              type: datetime                      
            }
          - "author"
          - "state"
          - {
              property: "email", 
              type: "email"
            }
          - text
      edit:
        fields:
          - { property: "conference", type_options: { disabled: true } }
          - {
              property: "createdAt",
              type: datetime,
              type_options: { disabled: true }              
            }          
      