version: "3"

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    ports: 
      - "6379"
      
volumes: 
     pgdata: