controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: '%app.default_locale%'
        
home_fallback:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /%app.default_locale%
        permanent: true
        
kernel:
    resource: ../../src/Kernel.php
    type: annotation
